# Generated by Django 5.0.6 on 2024-07-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
