# Generated by Django 5.0.6 on 2024-07-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_first_name_sponsor_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_sponsors',
            field=models.ManyToManyField(blank=True, related_name='students', to='common.studentsponsor'),
        ),
    ]
