# Generated by Django 5.0.6 on 2024-07-05 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_student_student_sponsors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_sponsors',
        ),
        migrations.AlterField(
            model_name='studentsponsor',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sponsors', to='common.sponsor'),
        ),
        migrations.AlterField(
            model_name='studentsponsor',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sponsors', to='common.student'),
        ),
    ]
